[theme]
primaryColor = "#915f02"              # Marrone-ocra per pulsanti e accenti
backgroundColor = "#f4e1b0"           # Ocra chiaro di sfondo principale
secondaryBackgroundColor = "#fff7da"  # Più chiaro per box e sidebar
textColor = "#2b1d00"                 # Testo scuro, alta leggibilità
font = "sans serif"


[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
